// gen_err_table_data.mjs - deterministic generator for src/err_table_data.cpp.
//
// Reads the SHA-256-pinned PandaSpy HMS asset (en.json) and emits two
// key-sorted {key, message} tables (hms + print_error) inside
// namespace obn::err::data. Node built-ins only - no packages, no network
// (the asset is fetched separately and pinned by hash before this runs).
//
// Determinism contract: same input bytes -> byte-identical output. Keys are
// sorted lexicographically (byte order for these ASCII hex keys); messages
// are emitted with a fixed escaping rule (see cEscape below) so the source
// file stays pure ASCII and never contains a run of escapes that could
// merge at parse time.
//
// Usage (the regeneration command recorded in the generated header):
//   node tools/gen_err_table_data.mjs "<path-to>/en.json" src/err_table_data.cpp

import { readFileSync, writeFileSync } from "node:fs";

// Full MIT license text verbatim from
// https://raw.githubusercontent.com/doomspork/PandaSpy/main/LICENSE
// (the license of the asset we adopt below).
const MIT_LICENSE = `MIT License

Copyright (c) 2026 Sean Callan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

// Provenance pins for the asset (verified at fetch time; refuse to generate
// from anything else - the plan gate re-checks the same pins).
const ASSET_URL = "https://raw.githubusercontent.com/doomspork/PandaSpy/main/crates/pandaspy-proto/assets/hms/en.json";
const ASSET_IN_REPO_PATH = "crates/pandaspy-proto/assets/hms/en.json";
const ASSET_BYTES = 552030;
const ASSET_SHA256 = "B7FD5358F3163B9B424FF4CD8D2A1F1B15519EFC5CFCA3D8ED31378CE05F3B64";

// Fixed-width octal escape for every byte outside printable ASCII (0x20-0x7E),
// normal \" and \\ for quotes/backslashes. Exactly three octal digits so an
// escape can never merge with a following literal digit.
function cEscape(s) {
  const bytes = Buffer.from(s, "utf8");
  let out = "";
  for (const b of bytes) {
    if (b === 0x5c) out += "\\\\";
    else if (b === 0x22) out += '\\"';
    else if (b >= 0x20 && b <= 0x7e) out += String.fromCharCode(b);
    else out += "\\" + b.toString(8).padStart(3, "0");
  }
  return out;
}

function table(name, entries, note) {
  const lines = [];
  lines.push(`// ${name}: ${entries.length} entries${note ? " - " + note : ""}`);
  lines.push(`const Entry ${name}[] = {`);
  for (const [key, message] of entries) {
    lines.push(`    {"${cEscape(key)}", "${cEscape(message)}"},`);
  }
  lines.push("};");
  return lines.join("\n");
}

function main() {
  const [inPath, outPath] = process.argv.slice(2);
  if (!inPath || !outPath) {
    process.stderr.write(
      'usage: node tools/gen_err_table_data.mjs "<path-to>/en.json" src/err_table_data.cpp\n');
    process.exit(2);
  }

  const raw = readFileSync(inPath);
  if (raw.length !== ASSET_BYTES) {
    process.stderr.write(
      `refusing: asset is ${raw.length} bytes, expected ${ASSET_BYTES}\n`);
    process.exit(1);
  }
  const sha = require("node:crypto").createHash("sha256").update(raw).digest("hex").toUpperCase();
  if (sha !== ASSET_SHA256) {
    process.stderr.write(`refusing: asset SHA-256 ${sha} != pinned ${ASSET_SHA256}\n`);
    process.exit(1);
  }

  const json = JSON.parse(raw.toString("utf8"));
  if (!json.hms || !json.errors) {
    process.stderr.write("refusing: asset missing hms/errors maps\n");
    process.exit(1);
  }

  const hms = Object.keys(json.hms).sort().map((k) => [k, json.hms[k]]);
  const errors = Object.keys(json.errors).sort().map((k) => [k, json.errors[k]]);

  const header = `// AUTO-GENERATED FILE - do not edit by hand.
//
// Generated by tools/gen_err_table_data.mjs from the PandaSpy HMS asset.
// Source repository: https://github.com/doomspork/PandaSpy
// Asset path (in source repo): ${ASSET_IN_REPO_PATH}
// Asset URL: ${ASSET_URL}
// Asset size: ${ASSET_BYTES} bytes
// Asset SHA-256: ${ASSET_SHA256}
// hms entries: ${hms.length}
// print_error (errors) entries: ${errors.length}
// Regeneration command:
//   node tools/gen_err_table_data.mjs "<path-to>/en.json" src/err_table_data.cpp
//
// ---------------------------------------------------------------------------
// The data tables below are adopted verbatim under the MIT License:
//
// ${MIT_LICENSE.split("\n").join("\n// ")}
// ---------------------------------------------------------------------------
//
// Key sort order: lexicographic (byte order) within each table.
// Lookup API: include/obn/err_table.hpp (namespace obn::err).

#include "obn/err_table.hpp"

`;

  const body = [
    "namespace obn::err::data {",
    "",
    table("hms_entries", hms, "16-lowercase-hex HMS keys"),
    "",
    `const std::size_t hms_count = ${hms.length};`,
    "",
    table("print_error_entries", errors, "8-lowercase-hex print_error keys"),
    "",
    `const std::size_t print_error_count = ${errors.length};`,
    "",
    "} // namespace obn::err::data",
    "",
  ].join("\n");

  writeFileSync(outPath, header + body, { encoding: "utf8" });
  process.stdout.write(
    `wrote ${outPath}: hms=${hms.length} print_error=${errors.length}\n`);
}

// node:crypto via createRequire (ESM module has no require()).
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);

main();
